routes/web.php
<?php

Route::middleware(['web', 'auth'])
    ->namespace('Rapture\NFLFantasy\Controllers')
    ->prefix('dashboard/nfl')
    ->name('dashboard.nfl.')
    ->group(function () {
        Route::resource('teams', 'TeamsController')->except(['show', 'create']);
        Route::resource('games', 'GamesController')->except(['show', 'create']);
        Route::resource('picks', 'PicksController')->only(['index', 'store']);
        Route::resource('results', 'ResultsController')->only(['index', 'show']);
        Route::resource('winners', 'WinnersController')->only(['edit', 'update']);
    });

resources/views/games/edit.blade.php
@extends('rapture::layouts.dashboard')

@section('content')
    @heading
        @lang('nfl::games.edit.title')

        @slot('after')
            <a href="{{ route('dashboard.nfl.games.index') }}" class="btn-pill">
                <em class="far fa-reply" aria-hidden="true"></em> @lang('rapture::actions.return')
            </a>
        @endslot
    @endheading

    @statuses

    <div class="content-builder">
        <div class="container">
            <form method="post" action="{{ route('dashboard.nfl.games.update', $week) }}">
                @csrf
                @method('PUT')

                <div class="row">
                    <div class="content">
                        <div class="box">
                            <div class="form-field">
                                <label for="name">@lang('rapture::field.name') <span class="required">@lang('rapture::field.required')</span></label>
                                <input type="text" name="label" id="name" value="{{ old('label', $week->label) }}">
                            </div>
                        </div>

                        <match-selection :teams='@json($teams)' :games='@json($week->games)'></match-selection>
                    </div>
                    <div class="sidebar">
                        <button type="submit" class="btn full">@lang('rapture::actions.save')</button>

                        <div class="widget">
                            <div class="form-field">
                                <label><em class="far fa-calendar-exclamation"></em>Pick cut off</label>
                                <input type="text" name="cut_off" class="datepicker" value="{{ old('cut_off', $week->cut_off) }}">
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('components')
    <script src="{{ asset('nfl/js/app.js') }}"></script>
@endpush

@push('styles')
    <link rel="stylesheet" href="{{ asset('nfl/css/style.css') }}">
@endpush

resources/views/games/index.blade.php
@extends('rapture::layouts.dashboard')

@section('content')
    @heading
        @lang('nfl::games.index.title')

        @slot('after')
            @can('nfl.games.create')
                <new-entry action="{{ route('dashboard.nfl.games.store') }}" placeholder="@lang('nfl::games.new_placeholder')" name="label">@lang('nfl::games.new_item')</new-entry>
            @endcan
        @endslot
    @endheading

    @statuses

    <div class="container">
        <table class="table striped">
            <tr>
                <th>@lang('rapture::field.name')</th>
                <th class="action"></th>
            </tr>
            @foreach ($weeks as $games)
                <tr>
                    <td>{{ $games->label }}</td>
                    <td class="action">
                        @can('nfl.games.edit')
                        @if ($games->locked())
                        <a href="{{ route('dashboard.nfl.winners.edit', $games->id) }}" title="Set winners">
                            <em class="far fa-trophy"></em>
                        </a>
                        @endif
                        <a href="{{ route('dashboard.nfl.games.edit', $games->id) }}" aria-label="@lang('rapture::actions.edit')">
                            <em class="far fa-pencil" aria-hidden="true" title="@lang('rapture::actions.edit_model', ['model' => $games->label])"></em>
                        </a>
                        @endcan
                        @can('nfl.games.destroy')
                        <delete-button action="{{ route('dashboard.nfl.games.destroy', $games->id) }}" aria-label="@lang('rapture::actions.delete')" title="@lang('rapture::actions.delete_model', ['model' => $games->label])"></delete-button>
                        @endcan
                    </td>
                </tr>
            @endforeach
        </table>

        {{ $weeks->links() }}
    </div>
@endsection

resources/views/picks/edit.blade.php
@extends('rapture::layouts.dashboard')

@section('content')
    @heading
        @lang('teams::package.edit.title')

        @slot('after')
            <a href="{{ route('dashboard.teams.index') }}" class="btn-pill">
                <em class="far fa-reply" aria-hidden="true"></em> @lang('rapture::actions.return')
            </a>
        @endslot
    @endheading

    @statuses

    <div class="content-builder">
        <div class="container">
            <form method="post" action="{{ route('dashboard.teams.update', $team) }}">
                @csrf
                @method('PUT')

                <div class="row">
                    <div class="content">
                        <div class="box">
                            <div class="form-field">
                                <label for="name">@lang('rapture::field.name') <span class="required">@lang('rapture::field.required')</span></label>
                                <input type="text" name="name" id="name" value="{{ old('name', $team->name) }}">
                            </div>
                        </div>
                    </div>
                    <div class="sidebar">
                        <button type="submit" class="btn full">@lang('rapture::actions.save')</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/picks/index.blade.php
@extends('rapture::layouts.dashboard')

@section('content')
    @heading
        @lang('nfl::games.index.title')
    @endheading

    <div class="tab-wrapper">
        <ul class="tab-headings">
            @foreach ($weeks as $week)
            <li class="tab{{ $currentWeek && $currentWeek->id === $week->id ? ' active' : '' }}"><a href="#tab{{ $week->id }}">{{ $week->label }}</a></li>
            @endforeach
        </ul>
    </div>

    @statuses

    @foreach ($weeks as $week)
        <div class="tab-body{{ $currentWeek && $currentWeek->id === $week->id ? ' active' : '' }}" id="tab{{ $week->id }}">
            <p class="cut-off">Close{{ $week->allowed() ? 's' : 'd' }} {{ $week->closes() }} @ 7 PM</p>
            <ul class="matches">
                @foreach ($week->games as $game)
                <li data-match="{{ $game->id }}">
                    <button type="button" class="team1{{ $game->pick && $game->pick->team_id === $game->team1->id ? ' active' : '' }}{{ $game->team1->id === $game->winner_id ? ' winner' : '' }}{{ !is_null($game->winner_id) ? ' locked' : '' }}" data-id="{{ $game->team1->id }}"{{ !$week->allowed() ? ' disabled' : '' }}>
                        <span>{{ $game->team1->name }}</span>
                        <img src="{{ $game->team1->logo }}">
                    </button>
                    <div class="spacer">VS</div>
                    <button type="button" class="team2{{ $game->pick && $game->pick->team_id === $game->team2->id ? ' active' : '' }}{{ $game->team2->id === $game->winner_id ? ' winner' : '' }}{{ !is_null($game->winner_id) ? ' locked' : '' }}" data-id="{{ $game->team2->id }}"{{ !$week->allowed() ? ' disabled' : '' }}>
                        <img src="{{ $game->team2->logo }}">
                        <span>{{ $game->team2->name }}</span>
                    </button>
                </li>
                @endforeach
            </ul>
        </div>
    @endforeach
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('nfl/css/picks.css') }}">
@endpush

@push('scripts')
    <script src="{{ asset('nfl/js/picks.js') }}"></script>
@endpush

resources/views/results/index.blade.php
@extends('rapture::layouts.dashboard')

@section('content')
    @heading
        Results
    @endheading

    <div class="tab-wrapper">
        <ul class="tab-headings">
            @foreach ($weeks as $week)
            <li class="tab{{ $currentWeek->id === $week->id ? ' active' : '' }}"><a href="#tab{{ $week->id }}">{{ $week->label }}</a></li>
            @endforeach
        </ul>
    </div>

    @statuses

    @foreach ($weeks as $week)
        <div class="tab-body{{ $currentWeek->id === $week->id ? ' active' : '' }}" id="tab{{ $week->id }}">
            @if ($winners->has($week->id) && $winners->get($week->id)->count() > 0)
                <div class="standings">
                    @foreach ($winners->get($week->id)->take(3) as $index => $result)
                    <div class="standing">
                        <span class="name">{{ $result->pluck('user.name')->implode(', ') }}</span>
                        <span class="total">
                            <em class="fal fa-trophy"></em> {{ $result->first()['correct'] }}
                        </span>
                        <div class="step">
                            <div class="inner"></div>
                        </div>
                    </div>
                    @endforeach
                    @for ($i = 3 - $winners->get($week->id)->count(); $i > 0; $i--)
                    <div class="standing">
                        <div class="step">
                            <div class="inner"></div>
                        </div>
                    </div>
                    @endfor
                </div>
                @if ($winners->get($week->id)->count() > 3)
                    <ol class="results">
                        @foreach ($winners->get($week->id)->slice(3) as $result)
                            <li>
                                <span class="name">{{ $result->pluck('user.name')->implode(', ') }}</span>
                                <span class="correct"><em class="fal fa-trophy"></em> {{ $result->first()['correct'] }}</span>
                            </li>
                        @endforeach
                    </ol>
                @endif
            @else
                <div class="standings">
                    @for ($i = 3; $i > 0; $i--)
                    <div class="standing">
                        <div class="step">
                            <div class="inner"></div>
                        </div>
                    </div>
                    @endfor
                </div>
            @endif
        </div>
    @endforeach
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('nfl/css/picks.css') }}">
@endpush

@push('scripts')
    <script src="{{ asset('nfl/js/picks.js') }}"></script>
@endpush

resources/views/winners/edit.blade.php
@extends('rapture::layouts.dashboard')

@section('content')
    @heading
        Enter Winners

        @slot('after')
            <a href="{{ route('dashboard.nfl.games.index') }}" class="btn-pill">
                <em class="far fa-reply" aria-hidden="true"></em> @lang('rapture::actions.return')
            </a>
        @endslot
    @endheading

    @statuses

    <div class="content-builder">
        <div class="container">
            <form method="post" action="{{ route('dashboard.nfl.winners.update', $week) }}">
                @csrf
                @method('PUT')

                <div class="row">
                    <div class="content">
                        <div class="box">
                            <ul class="matches">
                                @foreach ($week->games as $game)
                                <li>
                                    <button type="button" data-id="{{ $game->team1->id }}" class="{{ $game->team1->id === $game->winner_id ? 'active' : '' }}">
                                        <div class="team1">
                                            {{ $game->team1->name }}
                                        </div>
                                        <div class="team-logo">
                                            <img src="{{ asset($game->team1->logo) }}">
                                        </div>
                                    </button>
                                    <div class="spacer">VS</div>
                                    <button type="button" data-id="{{ $game->team2->id }}" class="{{ $game->team2->id === $game->winner_id ? 'active' : '' }}">
                                        <div class="team-logo">
                                            <img src="{{ asset($game->team2->logo) }}">
                                        </div>
                                        <div class="team2">
                                            {{ $game->team2->name }}
                                        </div>
                                    </button>
                                    <input type="hidden" name="game[{{ $game->id }}]" value="{{ $game->winner_id }}">
                                </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                    <div class="sidebar">
                        <button type="submit" class="btn full">@lang('rapture::actions.save')</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('nfl/js/winners.js') }}"></script>
@endpush

@push('styles')
    <link rel="stylesheet" href="{{ asset('nfl/css/style.css') }}">
@endpush